services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=search-cluster
      - discovery.seed_hosts=es02,es03
      #   - discovery.type=single-node
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9200:9200" # https
      - "9300:9300" #tcp
    networks:
      - es-bridge
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=search-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9201:9200" # https
      - "9301:9300" #tcp
    networks:
      - es-bridge
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=search-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9202:9200" # https
      - "9302:9300" #tcp
    networks:
      - es-bridge
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.3
    container_name: logstash
    environment:
      - xpack.monitoring.enabled=false
    ports:
      - 5000:5000
      - 9600:9600
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf # local file mapping
    depends_on:
      - es01
      - es02
      - es03
    networks:
      - es-bridge
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5601:5601
    # Elasticsearch Start Dependency
    depends_on:
      - es01
    networks:
      - es-bridge
networks:
  es-bridge:
    driver: bridge