server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset : UTF-8
      enabled: true
      force: true

spring:
  application:
    name: spring-blue
  datasource:
    master:
      hikari:
        jdbc-url: ${PROD_MASTER_JDBC_URL}
        username: ${PROD_MASTER_USERNAME}
        password: ${PROD_MASTER_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      hikari:
        jdbc-url: ${PROD_SLAVE_JDBC_URL}
        username: ${PROD_SLAVE_USERNAME}
        password: ${PROD_SLAVE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc.swagger-ui.path: /api-test

jwt.secret.key: ${secret_key}